### ISSUE TITLE
Memory errors with numpy ffts

### ISSUE THREAD

**Issue by ronpandolfi** [ronpandolfi/Xi-cam#4]
When running autocalibration, numpy's fft (frequently but not always) gives memory errors (although there is >80% remaining).
Solutions:
1. Switch to pyFFTW
2. overwrite existing array

Traceback:
```
Traceback (most recent call last):
  File "C:\Users\ronpa\PycharmProjects\xi-cam\xicam\threads.py", line 198, in run
    for status in self._method(*self.method_args, **self.method_kwargs):
  File "C:\Users\ronpa\PycharmProjects\xi-cam\pipeline\calibration.py", line 43, in fourierAutocorrelation
    config.activeExperiment.center = center_approx.center_approx(dimg.transformdata)
  File "C:\Users\ronpa\PycharmProjects\xi-cam\xicam\debugtools.py", line 18, in timed
    result = method(*args, **kw)
  File "C:\Users\ronpa\PycharmProjects\xi-cam\pipeline\center_approx.py", line 257, in center_approx
    con = signal.fftconvolve(img, img) / signal.fftconvolve(np.ones_like(img), np.ones_like(img))
  File "C:\Python27\lib\site-packages\scipy\signal\signaltools.py", line 366, in fftconvolve
    np.fft.rfftn(in2, fshape), fshape)[fslice].
  File "C:\Python27\lib\site-packages\numpy\fft\fftpack.py", line 1204, in irfftn
    a = irfft(a, s[-1], axes[-1], norm)
  File "C:\Python27\lib\site-packages\numpy\fft\fftpack.py", line 452, in irfft
    _real_fft_cache)
  File "C:\Python27\lib\site-packages\numpy\fft\fftpack.py", line 75, in _raw_fft
    z = zeros(s, a.dtype.char)
MemoryError
```

**Comment by ronpandolfi** [comment]
This is probably related to memory limitations in 32 bit python.
Solution: Build 64-bit installer

**Comment by ronpandolfi** [comment]
Solved with 64-bit installer.
